[3] mock DNS.resolve when testing
slab/safeurl-elixir pull request #6
Opened 2022-05-05 06:13 UTC by bhan-slab

2022-05-05 17:56 UTC, sheharyarn commented
I changed the base of this PR to the branch in #5 to simplify the git diff. Please merge #5 before this PR.

2022-05-05 22:11 UTC, sheharyarn requested changes
Mocking DNS in our own tests would be the wrong strategy. The goal in #3 is to disable DNS resolution when needed, which can be useful to other Elixir projects that use SafeURL.

My suggestion is to introduce a `resolve_dns` [config](https://github.com/slab/safeurl-elixir/blob/bc9f1ed421d4e3a6b6ee47ccd333e1f0728b13c3/mix.exs#L46-L53) that defaults to `true`. We should [resolve DNS](https://github.com/slab/safeurl-elixir/blob/96d4e672857521fd43123e314e855756d8ed3ec1/lib/safeurl.ex#L267-L270) only when this config is true.

2022-05-06 02:14 UTC, bhan-slab commented
> Mocking DNS in our own tests would be the wrong strategy. The goal in #3 is to disable DNS resolution when needed, which can be useful to other Elixir projects that use SafeURL.
> 
> My suggestion is to introduce a `resolve_dns` [config](https://github.com/slab/safeurl-elixir/blob/bc9f1ed421d4e3a6b6ee47ccd333e1f0728b13c3/mix.exs#L46-L53) that defaults to `true`. We should [resolve DNS](https://github.com/slab/safeurl-elixir/blob/96d4e672857521fd43123e314e855756d8ed3ec1/lib/safeurl.ex#L267-L270) only when this config is true.

what should the downstream behavior be when resolving DNS is turned off? the downstream logic relies on getting an IP address.

2022-05-06 03:32 UTC, martosaur commented
I think the biggest drawback of simply mocking calls to `DNS` module is that it won't work for other people who use this library.

@sheharyarn should we go with `DNSResolver` behavior pattern so that users could swap it for mock module in tests? If we make a config option to skip dns resolution people won't actually be able to test both positive and negative scenarios?

2022-05-06 22:27 UTC, sheharyarn commented
That's a really good point. My thinking is we don't want to prematurely optimize or build solutions to problems that have not been reported enough yet. But that said, simply plugging in a module in the config is a good solution for library users that offers a lot of flexibility.

We can just implement the `SafeURL.DNSResolver` behaviour with one `resolve(domain)` callback as you suggested, but leave out the behaviour implementation wrapper around the `DNS` module and directly use it in the config as `dns_resolver: DNS`.

2022-05-10 06:40 UTC, bhan-slab commented
@sheharyarn @martosaur thanks for the suggestions! i've implemented an approach using `behaviour`. could you take a look?

2022-05-10 17:54 UTC, martosaur approved these changes
Looks good! 🎉

2022-05-10 17:54 UTC, martosaur commented on mix.lock
> +  "meck": {:hex, :meck, "0.9.2", "85ccbab053f1db86c7ca240e9fc718170ee5bda03810a6292b5306bf31bae5f5", [:rebar3], [], "hexpm", "81344f561357dc40a8344afa53767c32669153355b626ea9fcbc8da6b3045826"},
these are not needed anymore?

2022-05-11 09:36 UTC, bhan-slab commented on mix.lock
> +  "meck": {:hex, :meck, "0.9.2", "85ccbab053f1db86c7ca240e9fc718170ee5bda03810a6292b5306bf31bae5f5", [:rebar3], [], "hexpm", "81344f561357dc40a8344afa53767c32669153355b626ea9fcbc8da6b3045826"},
removed, thanks!

2022-05-11 09:37 UTC, merged